# Generated by Django 4.1.3 on 2022-12-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkair_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=10)),
                ('pm10', models.IntegerField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='checkair_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.IntegerField(max_length=30)),
                ('pm10', models.IntegerField(default=0, max_length=20)),
            ],
        ),
    ]
